<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LogisticsPackingService.Application\LogisticsPackingService.Application.csproj" />
		<ProjectReference Include="..\LogisticsPackingService.Domain\LogisticsPackingService.Domain.csproj" />
	</ItemGroup>

</Project>